kube-prometheus-stack:
  alertmanager:
    alertmanagerSpec:
      image:
        tag: v0.28.1
    ingress:
      enabled: true
      hosts:
        - alertmanager-dev.localhost
      paths:
        - /
  grafana:
    image:
      tag: 12.2.0
    adminPassword: admin
    sidecar:
      dashboards:
        enabled: true
        labelValue: ""
    additionalDataSources:
     - name: prometheus-local
       type: prometheus
       uid: prometheus-local
       url: http://host.docker.internal:9090
       access: proxy
       isDefault: false
       jsonData:
         httpMethod: POST
         timeInterval: 15s
    ingress:
      enabled: true
      hosts:
        - grafana-dev.localhost
      paths:
        - /
  prometheus:
    prometheusSpec:
      image:
        tag: v3.6.0
    ingress:
      enabled: true
      hosts:
        - prometheus-dev.localhost
      paths:
        - /
  prometheus-node-exporter:
    prometheus:
      monitor:
        interval: 15s
